#!/bin/bash
# .openshift/action_hooks/deploy

# change into the application directory
cd $OPENSHIFT_REPO_DIR;

# composer commands
composer install --no-interaction --no-dev;
composer update;

# move example to .env
mv .env.example .env;

# generate an application key
php artisan key:generate;
