#!/bin/bash
# .openshift/action_hooks/deploy

# setup lets encrypt
# git clone https://github.com/letsencrypt/letsencrypt $OPENSHIFT_DATA_DIR/letsencrypt;
# sudo service nginx stop;
# cd $OPENSHIFT_DATA_DIR/letsencrypt;
# ./letsencrypt-auto certonly --non-interactive --agree-tos --email ryan.m.coble@gmail.com --domain stsb.coble.ninja --renew-by-default --webroot -w $OPENSHIFT_REPO_DIR/public;
# sudo service nginx start;

# change into the application directory
cd $OPENSHIFT_REPO_DIR;

# composer commands
composer install --no-interaction --no-dev;
composer update;

# migrate all the database changes
php artisan migrate --force;

# move example to .env
mv .env.production .env;

# generate an application key
php artisan key:generate;
